`timescale 1ns / 1ps
//////////////////////////////////////////////////////////////////////////////////
// Company: 
// Engineer: 
// 
// Create Date: 05/03/2026 01:30:13 PM
// Design Name: 
// Module Name: tb_resize_maxpooling_quant_parallel
// Project Name: 
// Target Devices: 
// Tool Versions: 
// Description: 
// 
// Dependencies: 
// 
// Revision:
// Revision 0.01 - File Created
// Additional Comments:
// 
//////////////////////////////////////////////////////////////////////////////////



module tb_resize_maxpooling_quant_parallel;

    // ============================================================
    // Parameters matching DUT
    // ============================================================

    localparam ADDR_WIDTH_BASE = 24;

    localparam IN_W      = 640;
    localparam IN_H      = 480;

    localparam OUT_SIZE  = 224;
    localparam SCALED_H  = 168;
    localparam PAD_TOP   = 28;

    localparam FP        = 16;
    localparam X_STEP    = 32'd187245;
    localparam Y_STEP    = 32'd187245;

    localparam integer IN_PIXELS  = IN_W * IN_H;
    localparam integer OUT_PIXELS = OUT_SIZE * OUT_SIZE;

    // ============================================================
    // Quantization config used by DUT and golden model
    // ============================================================
    //
    // Default setting:
    //     q = pixel_u8 - 128
    //
    // If you want to test other quant parameters, change these three
    // values. The golden model below will use the same values.
    // ============================================================

    localparam signed [31:0] SCALE_MULT  = 32'sd1;
    localparam        [5:0]  SCALE_SHIFT = 6'd0;
    localparam signed [7:0]  ZP          = -8'sd128;

    // ============================================================
    // File input/output
    // ============================================================

    localparam FRAME_HEX = "frame_640x480.hex";

    // Actual RTL capture
    localparam CAPTURE_R_HEX   = "rtl_capture_224_r.hex";
    localparam CAPTURE_G_HEX   = "rtl_capture_224_g.hex";
    localparam CAPTURE_B_HEX   = "rtl_capture_224_b.hex";
    localparam CAPTURE_RGB_HEX = "rtl_capture_224_rgb.hex";

    // Golden expected output generated by this TB
    localparam EXPECT_R_HEX    = "expected_224_r.hex";
    localparam EXPECT_G_HEX    = "expected_224_g.hex";
    localparam EXPECT_B_HEX    = "expected_224_b.hex";
    localparam EXPECT_RGB_HEX  = "expected_224_rgb.hex";

    // ============================================================
    // Clock / reset
    // ============================================================

    reg clk_i;
    reg resetn_i;

    initial begin
        clk_i = 1'b0;
        forever #5 clk_i = ~clk_i;   // 100 MHz for simulation
    end

    // ============================================================
    // DUT signals
    // ============================================================

    reg  [ADDR_WIDTH_BASE-1:0] cal_addr_base_i;
    reg                        cal_valid_i;
    wire                       cal_ready_o;

    wire [ADDR_WIDTH_BASE-1:0] fb_addr_o;
    reg  [15:0]                fb_pixel_data_i;

    wire                       ff_wr_rgb_buf_o;
    wire                       ff_tlast_pixel_o;
    wire signed [7:0]          ff_r_pixel_data_o;
    wire signed [7:0]          ff_g_pixel_data_o;
    wire signed [7:0]          ff_b_pixel_data_o;

    // ============================================================
    // DUT instance
    // ============================================================

    resize_maxpooling #(
        .ADDR_WIDTH_BASE (ADDR_WIDTH_BASE),
        .IN_W            (IN_W),
        .IN_H            (IN_H),
        .OUT_SIZE        (OUT_SIZE),
        .SCALED_H        (SCALED_H),
        .PAD_TOP         (PAD_TOP),
        .FP              (FP),
        .X_STEP          (X_STEP),
        .Y_STEP          (Y_STEP)
    ) dut (
        .clk_i                    (clk_i),
        .resetn_i                 (resetn_i),

        .scale_inf_mult_reg       (SCALE_MULT),
        .scale_inf_mult_shift_reg (SCALE_SHIFT),
        .zp_i                     (ZP),

        .cal_addr_base_i          (cal_addr_base_i),
        .cal_valid_i              (cal_valid_i),
        .cal_ready_o              (cal_ready_o),

        .fb_addr_o                (fb_addr_o),
        .fb_pixel_data_i          (fb_pixel_data_i),

        .ff_wr_rgb_buf_o          (ff_wr_rgb_buf_o),
        .ff_tlast_pixel_o         (ff_tlast_pixel_o),
        .ff_r_pixel_data_o        (ff_r_pixel_data_o),
        .ff_g_pixel_data_o        (ff_g_pixel_data_o),
        .ff_b_pixel_data_o        (ff_b_pixel_data_o)
    );

    // ============================================================
    // Frame buffer model
    // ============================================================
    //
    // frame_mem is loaded from frame_640x480.hex.
    //
    // Frame buffer latency = 1 clock:
    //
    //   cycle N:
    //      DUT drives fb_addr_o
    //
    //   cycle N+1:
    //      fb_pixel_data_i <= frame_mem[fb_addr_o]
    //
    // Each line in .hex is one RGB565 16-bit pixel.
    // Address is pixel address, not byte address.
    // ============================================================

    reg [15:0] frame_mem [0:IN_PIXELS-1];

    always @(posedge clk_i) begin
        if (fb_addr_o < IN_PIXELS)
            fb_pixel_data_i <= frame_mem[fb_addr_o];
        else
            fb_pixel_data_i <= 16'h0000;
    end

    // ============================================================
    // Golden model: RGB565 expand to RGB888
    // ============================================================

    function automatic [7:0] expand_r5_to_r8;
        input [4:0] r5;
        begin
            expand_r5_to_r8 = {r5, r5[4:2]};
        end
    endfunction

    function automatic [7:0] expand_g6_to_g8;
        input [5:0] g6;
        begin
            expand_g6_to_g8 = {g6, g6[5:4]};
        end
    endfunction

    function automatic [7:0] expand_b5_to_b8;
        input [4:0] b5;
        begin
            expand_b5_to_b8 = {b5, b5[4:2]};
        end
    endfunction

    // ============================================================
    // Golden model: quantize one uint8 pixel to signed int8
    // ============================================================
    //
    // This mirrors the RTL quantizer:
    //
    //   stage1 = pixel_u8 * SCALE_MULT
    //   stage2 = stage1 + round_value - negative_correction
    //   stage3 = stage2 >>> SCALE_SHIFT
    //   stage4 = stage3 + ZP
    //   stage5 = clamp to signed int8 [-128, 127]
    //
    // Return value is two's-complement signed int8.
    // ============================================================

    function automatic signed [7:0] golden_quant_u8;
        input [7:0] pixel_u8;

        reg signed [63:0] stage1;
        reg signed [63:0] stage2;
        reg signed [63:0] stage3;
        reg signed [63:0] stage4;
        reg signed [63:0] round_value;
        begin
            stage1 = $signed({1'b0, pixel_u8}) * SCALE_MULT;

            if (SCALE_SHIFT != 6'd0)
                round_value = 64'sd1 <<< (SCALE_SHIFT - 6'd1);
            else
                round_value = 64'sd0;

            stage2 = stage1 + round_value -
                     (((SCALE_SHIFT != 6'd0) && (stage1 < 0)) ? 64'sd1 : 64'sd0);

            if (SCALE_SHIFT != 6'd0)
                stage3 = stage2 >>> SCALE_SHIFT;
            else
                stage3 = stage2;

            stage4 = stage3 + ZP;

            if (stage4 > 64'sd127)
                golden_quant_u8 = 8'sd127;
            else if (stage4 < -64'sd128)
                golden_quant_u8 = -8'sd128;
            else
                golden_quant_u8 = stage4[7:0];
        end
    endfunction

    // ============================================================
    // Golden model: expected quantized R/G/B for one output pixel
    // ============================================================
    //
    // Return format:
    //   [23:16] = qR
    //   [15:8]  = qG
    //   [7:0]   = qB
    // ============================================================

    function automatic [23:0] expected_qrgb;
        input integer out_y;
        input integer out_x;

        integer img_y;

        integer src_x0;
        integer src_x1;
        integer src_y0;
        integer src_y1;

        integer xx;
        integer yy;
        integer addr;

        reg [15:0] pix;

        reg [4:0] max_r5;
        reg [5:0] max_g6;
        reg [4:0] max_b5;

        reg [7:0] r8;
        reg [7:0] g8;
        reg [7:0] b8;

        reg signed [7:0] qr;
        reg signed [7:0] qg;
        reg signed [7:0] qb;

        begin
            if ((out_y < PAD_TOP) || (out_y >= (PAD_TOP + SCALED_H))) begin
                // Padding RGB565 = 0, so R8/G8/B8 = 0.
                r8 = 8'd0;
                g8 = 8'd0;
                b8 = 8'd0;
            end else begin
                img_y = out_y - PAD_TOP;

                src_x0 = (out_x * X_STEP) >> FP;

                if (out_x == OUT_SIZE - 1)
                    src_x1 = IN_W - 1;
                else
                    src_x1 = (((out_x + 1) * X_STEP) >> FP) - 1;

                src_y0 = (img_y * Y_STEP) >> FP;

                if (img_y == SCALED_H - 1)
                    src_y1 = IN_H - 1;
                else
                    src_y1 = (((img_y + 1) * Y_STEP) >> FP) - 1;

                max_r5 = 5'd0;
                max_g6 = 6'd0;
                max_b5 = 5'd0;

                for (yy = src_y0; yy <= src_y1; yy = yy + 1) begin
                    for (xx = src_x0; xx <= src_x1; xx = xx + 1) begin
                        addr = yy * IN_W + xx;
                        pix  = frame_mem[addr];

                        if (pix[15:11] > max_r5)
                            max_r5 = pix[15:11];

                        if (pix[10:5] > max_g6)
                            max_g6 = pix[10:5];

                        if (pix[4:0] > max_b5)
                            max_b5 = pix[4:0];
                    end
                end

                r8 = expand_r5_to_r8(max_r5);
                g8 = expand_g6_to_g8(max_g6);
                b8 = expand_b5_to_b8(max_b5);
            end

            qr = golden_quant_u8(r8);
            qg = golden_quant_u8(g8);
            qb = golden_quant_u8(b8);

            expected_qrgb = {qr[7:0], qg[7:0], qb[7:0]};
        end
    endfunction

    // ============================================================
    // Capture output FIFO writes and self-check
    // ============================================================

    integer cap_r_fd;
    integer cap_g_fd;
    integer cap_b_fd;
    integer cap_rgb_fd;

    integer exp_r_fd;
    integer exp_g_fd;
    integer exp_b_fd;
    integer exp_rgb_fd;

    integer capture_count;
    integer row_pixel_count;
    integer error_count;
    integer tlast_error_count;

    reg [23:0] exp_qrgb;
    reg [7:0]  exp_qr;
    reg [7:0]  exp_qg;
    reg [7:0]  exp_qb;

    integer current_capture_y;
    integer current_capture_x;

    always @(posedge clk_i) begin
        #1;

        if (ff_wr_rgb_buf_o) begin
            current_capture_y = capture_count / OUT_SIZE;
            current_capture_x = capture_count % OUT_SIZE;

            exp_qrgb = expected_qrgb(current_capture_y, current_capture_x);
            exp_qr   = exp_qrgb[23:16];
            exp_qg   = exp_qrgb[15:8];
            exp_qb   = exp_qrgb[7:0];

            // Write actual RTL outputs.
            $fwrite(cap_r_fd,   "%02h\n", ff_r_pixel_data_o[7:0]);
            $fwrite(cap_g_fd,   "%02h\n", ff_g_pixel_data_o[7:0]);
            $fwrite(cap_b_fd,   "%02h\n", ff_b_pixel_data_o[7:0]);
            $fwrite(cap_rgb_fd, "%02h%02h%02h\n",
                    ff_r_pixel_data_o[7:0],
                    ff_g_pixel_data_o[7:0],
                    ff_b_pixel_data_o[7:0]);

            // Write golden expected outputs too, so you can diff files.
            $fwrite(exp_r_fd,   "%02h\n", exp_qr);
            $fwrite(exp_g_fd,   "%02h\n", exp_qg);
            $fwrite(exp_b_fd,   "%02h\n", exp_qb);
            $fwrite(exp_rgb_fd, "%02h%02h%02h\n", exp_qr, exp_qg, exp_qb);

            // Self-check actual vs expected.
            if (ff_r_pixel_data_o[7:0] !== exp_qr) begin
                $display("[%0t] ERROR R y=%0d x=%0d got=%02h expected=%02h",
                         $time, current_capture_y, current_capture_x,
                         ff_r_pixel_data_o[7:0], exp_qr);
                error_count = error_count + 1;
            end

            if (ff_g_pixel_data_o[7:0] !== exp_qg) begin
                $display("[%0t] ERROR G y=%0d x=%0d got=%02h expected=%02h",
                         $time, current_capture_y, current_capture_x,
                         ff_g_pixel_data_o[7:0], exp_qg);
                error_count = error_count + 1;
            end

            if (ff_b_pixel_data_o[7:0] !== exp_qb) begin
                $display("[%0t] ERROR B y=%0d x=%0d got=%02h expected=%02h",
                         $time, current_capture_y, current_capture_x,
                         ff_b_pixel_data_o[7:0], exp_qb);
                error_count = error_count + 1;
            end

            // TLAST check: only last pixel of each row.
            if (row_pixel_count == OUT_SIZE - 1) begin
                if (ff_tlast_pixel_o !== 1'b1) begin
                    $display("[%0t] ERROR: ff_tlast_pixel_o should be 1 at y=%0d x=%0d",
                             $time, current_capture_y, current_capture_x);
                    tlast_error_count = tlast_error_count + 1;
                end
                row_pixel_count = 0;
            end else begin
                if (ff_tlast_pixel_o !== 1'b0) begin
                    $display("[%0t] ERROR: ff_tlast_pixel_o should be 0 at y=%0d x=%0d",
                             $time, current_capture_y, current_capture_x);
                    tlast_error_count = tlast_error_count + 1;
                end
                row_pixel_count = row_pixel_count + 1;
            end

            capture_count = capture_count + 1;
        end
    end

    // ============================================================
    // DMA task: one handshake = one output row
    // ============================================================

    task automatic send_row_request;
        input integer row_idx;
        begin
            @(negedge clk_i);

            cal_addr_base_i = row_idx * OUT_SIZE;
            cal_valid_i     = 1'b1;

            while (cal_ready_o !== 1'b1) begin
                @(posedge clk_i);
                #1;
                @(negedge clk_i);
            end

            // Handshake at next posedge
            @(posedge clk_i);
            #1;

            @(negedge clk_i);
            cal_valid_i = 1'b0;
        end
    endtask

    task automatic wait_row_done_by_tlast;
        input integer row_idx;
        integer timeout_count;
        integer start_count;
        begin
            timeout_count = 0;
            start_count   = capture_count;

            while (capture_count < start_count + OUT_SIZE) begin
                @(posedge clk_i);
                #1;
                timeout_count = timeout_count + 1;

                if (timeout_count > 50000) begin
                    $display("[%0t] ERROR: timeout waiting row %0d. captured=%0d expected_at_least=%0d",
                             $time, row_idx, capture_count, start_count + OUT_SIZE);
                    $finish;
                end
            end

            repeat (3) begin
                @(posedge clk_i);
                #1;
            end

            if (cal_ready_o !== 1'b1) begin
                $display("[%0t] ERROR: cal_ready_o should be high after row %0d",
                         $time, row_idx);
                tlast_error_count = tlast_error_count + 1;
            end
        end
    endtask

    task automatic run_one_row;
        input integer row_idx;
        begin
            send_row_request(row_idx);
            wait_row_done_by_tlast(row_idx);
        end
    endtask

    // ============================================================
    // Main test
    // ============================================================

    integer r;

    initial begin
        $dumpfile("tb_resize_maxpooling_quant_parallel.vcd");
        $dumpvars(0, tb_resize_maxpooling_quant_parallel);

        $display("=================================================");
        $display("TB resize_maxpooling_quant_parallel started");
        $display("Input  hex: %s", FRAME_HEX);
        $display("Actual R hex: %s", CAPTURE_R_HEX);
        $display("Actual G hex: %s", CAPTURE_G_HEX);
        $display("Actual B hex: %s", CAPTURE_B_HEX);
        $display("=================================================");
        $display("Quant config:");
        $display("  SCALE_MULT  = %0d", SCALE_MULT);
        $display("  SCALE_SHIFT = %0d", SCALE_SHIFT);
        $display("  ZP          = %0d", ZP);
        $display("=================================================");

        // Load frame buffer
        $readmemh(FRAME_HEX, frame_mem);

        // Open actual capture files
        cap_r_fd   = $fopen(CAPTURE_R_HEX, "w");
        cap_g_fd   = $fopen(CAPTURE_G_HEX, "w");
        cap_b_fd   = $fopen(CAPTURE_B_HEX, "w");
        cap_rgb_fd = $fopen(CAPTURE_RGB_HEX, "w");

        // Open expected files
        exp_r_fd   = $fopen(EXPECT_R_HEX, "w");
        exp_g_fd   = $fopen(EXPECT_G_HEX, "w");
        exp_b_fd   = $fopen(EXPECT_B_HEX, "w");
        exp_rgb_fd = $fopen(EXPECT_RGB_HEX, "w");

        if ((cap_r_fd == 0) || (cap_g_fd == 0) || (cap_b_fd == 0) || (cap_rgb_fd == 0) ||
            (exp_r_fd == 0) || (exp_g_fd == 0) || (exp_b_fd == 0) || (exp_rgb_fd == 0)) begin
            $display("ERROR: cannot open one or more output files");
            $finish;
        end

        capture_count     = 0;
        row_pixel_count   = 0;
        error_count       = 0;
        tlast_error_count = 0;

        resetn_i        = 1'b0;
        cal_valid_i     = 1'b0;
        cal_addr_base_i = {ADDR_WIDTH_BASE{1'b0}};
        fb_pixel_data_i = 16'h0000;

        repeat (10) @(posedge clk_i);
        resetn_i = 1'b1;
        repeat (5) @(posedge clk_i);
        #1;

        if (cal_ready_o !== 1'b1) begin
            $display("[%0t] ERROR: cal_ready_o should be high after reset", $time);
            tlast_error_count = tlast_error_count + 1;
        end

        // Run full 224 rows.
        // cal_addr_base_i:
        //   row 0 -> 0
        //   row 1 -> 224
        //   row 2 -> 448
        //   ...
        for (r = 0; r < OUT_SIZE; r = r + 1) begin
            $display("[%0t] Start row %0d, base addr %0d", $time, r, r * OUT_SIZE);
            run_one_row(r);
        end

        repeat (20) @(posedge clk_i);
        #1;

        $fclose(cap_r_fd);
        $fclose(cap_g_fd);
        $fclose(cap_b_fd);
        $fclose(cap_rgb_fd);

        $fclose(exp_r_fd);
        $fclose(exp_g_fd);
        $fclose(exp_b_fd);
        $fclose(exp_rgb_fd);

        $display("=================================================");
        $display("Captured pixels = %0d", capture_count);
        $display("Expected pixels = %0d", OUT_PIXELS);
        $display("Data errors     = %0d", error_count);
        $display("TLAST errors    = %0d", tlast_error_count);
        $display("=================================================");

        if (capture_count != OUT_PIXELS) begin
            $display("TEST FAILED: output pixel count mismatch");
        end else if (error_count != 0) begin
            $display("TEST FAILED: quantized data mismatch");
        end else if (tlast_error_count != 0) begin
            $display("TEST FAILED: TLAST/ready errors");
        end else begin
            $display("TEST PASSED");
            $display("");
            $display("You can also diff generated files:");
            $display("  diff expected_224_r.hex rtl_capture_224_r.hex");
            $display("  diff expected_224_g.hex rtl_capture_224_g.hex");
            $display("  diff expected_224_b.hex rtl_capture_224_b.hex");
            $display("  diff expected_224_rgb.hex rtl_capture_224_rgb.hex");
        end

        $finish;
    end

endmodule